name: Run Hello Script

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gemini-cli-app .

      - name: Run script in Docker container
        run: docker run gemini-cli-app
